### ISSUE TITLE
Partners Section On Website Homepage

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#11]
Going into the future we would be having a partners section on the homepage.
This month would be our first partner collaboration with [https://www.instagram.com/officialhumansofqueer/](OHOQ)
Design Reference
![WhatsApp Image 2023-04-29 at 13 34 47](https://user-images.githubusercontent.com/28837599/235292006-fb9ed904-074e-4e98-8b79-1bba383e21af.jpeg)

Another Sample Design
https://www.thepijam.org/ -> bottom of page

**Comment by plutoniumm** [comment]
- which section will this be under?
- How many partners are expected in
- - immediately
- - within 3 months
- - within 1 year

**Comment by Harihargmenon** [comment]
Page: https://barabariproject.org/ (Main Homepage)
Section: Above the footer
Partners: 
Immediately -> 1
3 Months -> 1 - 3 
1 year from now -> 4 - 7 (max)
