### ISSUE TITLE
[FEAT] Donation Page

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#13]
**Describe the feature you'd like**
Adding a page where people can come and donate.

**Additional context**
Ability to scan the QR and make a payment
Read about how the money would be used

**Comment by Harihargmenon** [comment]
![Template Design](https://github.com/Barabari-Project/Barabari-Project/assets/28837599/1548dbaa-47e2-4e58-af80-0ba9ca2a5e4a)

**Comment by plutoniumm** [comment]
Assigning to @realshivesh

**Comment by plutoniumm** [comment]
@Harihargmenon please add all text as text and the URL of the QR code also
