### ISSUE TITLE
[FEAT] About Us Page

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#14]
Adding an About Us page accessible via an option on the top left navigation bar

Details about content + design + feature
https://docs.google.com/document/d/1ancRPA56aCWNvrfWeyXX_LdKOxeI1w9IN_1fiGYJOKE/edit?usp=sharing

**Comment by plutoniumm** [comment]
to replace current `/#about` (dev build) , separate `/about` not neede

**Comment by plutoniumm** [comment]
same as `#20`
