### ISSUE TITLE
[BUG] Updating the achievements section on the homepage

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#19]
Section contains 3 segments now, need to update segment names and icons

Details about new segments and icons :
https://docs.google.com/document/d/1FHtz7kbhdAh1WeE6ktLjxi4AxuIdHeETsEGn8eMp5ps/edit?usp=sharing

**Comment by plutoniumm** [comment]
TODO: Row does not flex + Add images

**Comment by plutoniumm** [comment]
need a demo/wireframe for this
it is unclear how to add an `icon`, `number` and, a `description`
