### ISSUE TITLE
[FEAT] Adding Programs Section to Homepage

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#20]
Replacing this section from the current homepage with the **programs section** being made on the About Us page. Adding the same component on the homepage as well
Current section for reference 
https://drive.google.com/file/d/19wIYfik8-fZN8QCVRXn_St-jE7l7441K/view?usp=sharing

**Comment by Harihargmenon** [comment]
Images (Can choose any 2)
https://drive.google.com/file/d/1x0cxgiJILrcyraZLwfSAs3FYxihoN9d8/view?usp=sharing

https://drive.google.com/file/d/1m4ZTV72Kti8A141GHz_Aac7Lg-XmMFSZ/view?usp=drive_link

https://drive.google.com/file/d/1I7nAL_oAfJs--dGX1hgn5uEauIFvQP8k/view?usp=drive_link

**Comment by plutoniumm** [comment]
closed by #3c8132358af0d6870eca4369c50655567e667469
