### ISSUE TITLE
[FEAT] Updates To Summary Section

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#21]
Update the text and image of the summary sections below the nav bar
New Image + Text
https://docs.google.com/document/d/1KRHa6e3IBjtnB24YjuA3CAXHsXt8zo1LnuIaKiWUC6k/edit?usp=sharing

**Comment by plutoniumm** [comment]
TODO: Add images + does not flex-wrap row

**Comment by plutoniumm** [comment]
this issue is in direct conflict with #20 
Which one needs to be implemented?

**Comment by Harihargmenon** [comment]
https://drive.google.com/file/d/1Zy7h_fdrJkXMH1BRUNAUxPLfu8SzA5-d/view?usp=sharing
This is the summary page
In this, the text and image have to change as per the doc link given above

The issue in #20 
Is to replace the program details page
https://drive.google.com/file/d/19wIYfik8-fZN8QCVRXn_St-jE7l7441K/view?usp=sharing (reference image)

With the programs page made in the About us section

**Comment by plutoniumm** [comment]
Image size too low, image will not be changed
min-size needed is 1200px

**Comment by plutoniumm** [comment]
new text too long, stick to less than 180ch

due to infeasible changes issue will be closed
