### ISSUE TITLE
[FEAT] Reducing size of image so that CTA is visible on first load - Mobile Website

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#26]
We need to shorten the image height so that on the first load all CTAs are visible without needing to scroll.

Image reference for current screen
https://drive.google.com/file/d/1ArlIg8wiOgSEAMXhJXJ75d4WkJauoPsJ/view?usp=sharing

**Comment by plutoniumm** [comment]
too complicated to implement because of how screensize is calculated differently on different devices
