### ISSUE TITLE
[BUG] NavBar Highlight Styling Issue

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#29]
**Describe the bug**
The  Nav Bar text is not visible clearly since the background image has white walls.

**To Reproduce**
Open https://barabariproject.org/

**Expected behaviour**
Make the text clearer by adding a dark padding behind the Nav Bar
OR
Add Black Border Text  highlighting.

**Additional context**
We can use any styling change to make the nav bar pop out

**Comment by plutoniumm** [comment]
> Add Black Border Text highlighting

it already has black border and that does not seem to help

> adding a dark padding

what does dark padding mean? can you link some examples?
