### ISSUE TITLE
Extra text underline and colour change on homepage CTA texts

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#31]
### Describe the bug

<img width="1792" alt="Screenshot 2023-09-17 at 10 54 51 PM" src="https://github.com/Barabari-Project/Barabari-Project/assets/28837599/5ab47979-2237-4b71-802b-773896b7593c">

### Reproduction

https://barabariproject.org/

### System Info

```shell
NA
```

### Comments

Got updated in latest code release

### Severity

annoyance (low priority)

**Comment by plutoniumm** [comment]
this is not a bug

it is deliberately done for accessibility
