### ISSUE TITLE
Mobile View Donation Page Text & Image Size Update

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#34]
### Describe the bug

1. The text in mobile view is getting cut due to large size
2. The QR scanner looks too large

### Reproduction

Go to https://barabariproject.org/donate on a mobile phone (preferably android)

### System Info

```shell
Mobile Web View
```

### Comments

Reduce the overall size of the image and the text

### Severity

minor impact (medium priority)

**Comment by plutoniumm** [comment]
closing due to insufficient/wrong context information
