### ISSUE TITLE
Update the Footer Text On All Pages

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#35]
### Describe the feature
Change the text below the Org name on the footer

**Current String** - 1 Line
Universal Access To Tech Education

**New Required String** - 2 Lines
Section 8 Non-Profit
80G/12A Compliant

### Configuration

- [ ] This is a demo
- [ ] Platform Specific

### Alternatives Considered

No alternatives, just text change

### Comments

We have feedback that our official compliance and registration should be displayed on our pages more evidently.

**Comment by plutoniumm** [comment]
not a feature
please report as bug or compat fix
