### ISSUE TITLE
Previous Tab Highlight Bug

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#7]
Sometimes (not always) while going through different tabs on the web page a previously selected tab remains highlighted. The new page does not get highlighted 

Eg : Check the  attached image 
Selected Page -> Volunteering, Highltedv-> Mentor Page

https://drive.google.com/file/d/1psVJgowE_7V2wZeQwCARc2gaMjVGPQz6/view?usp=sharing

**Comment by Harihargmenon** [comment]
Not able to recreate it always, hence added a ss

**Comment by plutoniumm** [comment]
Unable to reproduce will be closed
