### ISSUE TITLE
Mobile View Header (All Pages)

### ISSUE THREAD

**Issue by Harihargmenon** [Barabari-Project/Barabari-Project#9]
![Mobile View Header](https://user-images.githubusercontent.com/28837599/235289673-38955729-239e-406a-85a1-ce3d7e401274.jpeg)

The header(logo + text) is aligned somewhere in the middle and looks slightly off.
Let's only have the logo and the hamburger menu button and increase the logo size.
So it would be one icon to the left and one to the right. Then if needed we can add the text (The Barabari Project) to the middle of the screen

**Comment by plutoniumm** [comment]
unable to reproduce will be closed

**Comment by Harihargmenon** [comment]
Can you send ss of what you are seeing on your mobile screen ?

**Comment by plutoniumm** [comment]
<img width="375" alt="Home  The Barabari Project" src="https://user-images.githubusercontent.com/51614345/235416275-cf4d23f1-07cd-4ba3-b63d-dcb12bd79fc2.png">
